Repository choderalab/openmmtools, pull requests merged in 2022-04, with the labels that each got.

#565 Real time analysis dynamic naming from reporter
  openmmtools/multistate/multistateanalyzer.py
  openmmtools/multistate/multistatereporter.py
  openmmtools/tests/test_sampling.py
Labels: :arrow_up: high-priority

#555 Added velocities to checkpoint file.
  openmmtools/multistate/multistatereporter.py
Labels: :bug: bug, :arrow_up: high-priority

#573 Fix failing windows CI
  .github/workflows/CI.yml
Labels: :bug: bug
